In [1]:
import pandas as pd
import json

In [2]:
# 1. Buka dan baca file JSON-nya
with open('C:\\Users\\nurul\\OneDrive\\Desktop\\data-science\\data\\competency_map.json', 'r') as file:
    data_json = json.load(file)

In [3]:
rows = []

In [4]:
# 3. Looping untuk bongkar isi JSON
for role_name, role_info in data_json.items():
    domain = role_info.get('domain')
    role_family = role_info.get('role_family')
    
    # Masuk ke dalam list competencies
    for comp in role_info.get('competencies', []):
        rows.append({
            'target_role': role_name,
            'domain': domain,
            'role_family': role_family,
            'competency_id': comp.get('competency_id'),
            'competency_name': comp.get('competency'),
            'weight': comp.get('weight'),
            'total_skills': len(comp.get('related_skills', [])),
            'related_skills': ", ".join(comp.get('related_skills', []))
        })

In [5]:
# 4. Ubah jadi Pandas DataFrame
df_comp = pd.DataFrame(rows)

In [6]:
# Tampilkan 15 baris pertama
df_comp.head(15)

,target_role,domain,role_family,competency_id,competency_name,weight,total_skills,related_skills
0,Data Analyst,Information & Technology,Data & AI,data_analyst_1,Data Analytics & Cleaning,0.35,5,"sql, excel, pandas, numpy, data cleaning"
1,Data Analyst,Information & Technology,Data & AI,data_analyst_2,Data Visualization & Dashboard Optimization,0.35,4,"tableau, power bi, google looker studio, bigquery"
2,Data Analyst,Information & Technology,Data & AI,data_analyst_3,Business Intelligence Reporting,0.30,4,"business intelligence, data analytics, communi..."
3,Data Scientist,Information & Technology,Data & AI,data_scientist_1,Data Science & Exploratory Modeling,0.35,4,"python, scikit-learn, predictive modelling, st..."
4,Data Scientist,Information & Technology,Data & AI,data_scientist_2,Machine Learning Evaluation & Tuning,0.35,4,"machine learning, tensorflow, hyperparameter t..."
5,Data Scientist,Information & Technology,Data & AI,data_scientist_3,Data Engineering Foundations,0.30,4,"sql, python, data pipelines, data extraction"
6,AI Engineer,Information & Technology,Data & AI,ai_engineer_1,Deep Learning Architecture Design,0.35,4,"deep learning, tensorflow, pytorch, python"
7,AI Engineer,Information & Technology,Data & AI,ai_engineer_2,Natural Language Processing & Generative AI,0.35,4,"natural language processing, prompt engineerin..."
8,AI Engineer,Information & Technology,Data & AI,ai_engineer_3,Computer Vision Application Systems,0.30,4,"computer vision, opencv, image augmentation, o..."
9,ML Engineer,Information & Technology,Data & AI,ml_engineer_1,Model Deployment & Containerization,0.35,4,"model deployment, python, docker, mlops"
10,ML Engineer,Information & Technology,Data & AI,ml_engineer_2,Automated MLOps Pipelines,0.35,4,"mlops, ci/cd, data preprocessing, feature engi..."
11,ML Engineer,Information & Technology,Data & AI,ml_engineer_3,Model Monitoring & Drift Detection,0.30,4,"mlops, hyperparameter tuning, tensorflow, metr..."
12,Cloud Engineer,Information & Technology,"Infrastructure, Cloud & Security",cloud_engineer_1,Cloud Infrastructure Setup,0.35,3,"aws, cloud deployment, networking"
13,Cloud Engineer,Information & Technology,"Infrastructure, Cloud & Security",cloud_engineer_2,Container & Orchestration,0.35,3,"docker, kubernetes, linux"
14,Cloud Engineer,Information & Technology,"Infrastructure, Cloud & Security",cloud_engineer_3,Monitoring & Reliability,0.30,3,"monitoring, linux, networking"

In [7]:
df_comp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   target_role      48 non-null     object
 1   domain           48 non-null     object
 2   role_family      48 non-null     object
 3   competency_id    48 non-null     object
 4   competency_name  48 non-null     object
 5   weight           48 non-null     float64
 6   total_skills     48 non-null     int64
 7   related_skills   48 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 3.1+ KB

In [8]:
#  Cek Integritas Bobot (Weight) per Role
#  Harusnya semua output angka di sini bernilai 1.0
df_comp.groupby('target_role')['weight'].sum()

target_role
AI Engineer               1.0
Android Developer         1.0
Backend Developer         1.0
Cloud Engineer            1.0
Cybersecurity Analyst     1.0
Data Analyst              1.0
Data Scientist            1.0
DevOps Engineer           1.0
Frontend Developer        1.0
Full Stack Developer      1.0
ML Engineer               1.0
Manual QA Tester          1.0
Mobile Developer          1.0
QA Automation Engineer    1.0
Software Tester           1.0
iOS Developer             1.0
Name: weight, dtype: float64

In [9]:
# Cek Sebaran Kompetensi per Role Family
df_comp['role_family'].value_counts()

role_family
Data & AI                           12
Infrastructure, Cloud & Security     9
Web Development                      9
Mobile Development                   9
Software Tester                      9
Name: count, dtype: int64

In [10]:
# Cek Kompetensi yang Paling Banyak Butuh Skill
df_comp.sort_values(by='total_skills', ascending=False)[['target_role', 'competency_name', 'related_skills']].head()

,target_role,competency_name,related_skills
0,Data Analyst,Data Analytics & Cleaning,"sql, excel, pandas, numpy, data cleaning"
21,Frontend Developer,User Interface UI Engineering,"html, css, bootstrap, tailwind css, web design"
33,iOS Developer,Native Apple Interface Optimization,"swift, xcode, swiftui, autolayout, uikit"
1,Data Analyst,Data Visualization & Dashboard Optimization,"tableau, power bi, google looker studio, bigquery"
4,Data Scientist,Machine Learning Evaluation & Tuning,"machine learning, tensorflow, hyperparameter t..."